### ISSUE TITLE
`eth_sandbox` from paradigm-ctf-infrastructure not compatible with CTF 2021

### ISSUE THREAD

**Issue by 0xYYY** [paradigmxyz/paradigm-ctf-2021#23]
# Issue
Run the `babyrev` challenge, `nc babyrev 31337 31338`, then connecting to it with `nc localhost 31337` will encounter the following error:
```
Traceback (most recent call last):
  File "/home/ctf/chal.py", line 5, in <module>
    eth_sandbox.new_launch_instance_action(deploy_value=Web3.toWei(50, 'ether')),
TypeError: new_launch_instance_action() got an unexpected keyword argument
```

# Cause
I believe the commit 46974f891c84c7b4b473f35b19394674f1d20c2b updated the infra to build images with the code from https://github.com/paradigmxyz/paradigm-ctf-infrastructure, but the `eth_sandbox` package there is not compatible with 2021 CTF.

`chal.py` in `babyrev`:
https://github.com/paradigmxyz/paradigm-ctf-2021/blob/eedc32d5e3367cbfd2a45601e026572ea39ddedb/babyrev/public/deploy/chal.py#L4-L7

Signature of `eth_sandbox.new_launch_instance_action` in [paradigm-ctf-infrastructure](https://github.com/paradigmxyz/paradigm-ctf-infrastructure/blob/99f6cc7fbad72c164813f3fc108c4935cd487ac6/images/eth-challenge-base/eth_sandbox/launcher.py#L80-L82)
```
def new_launch_instance_action(
    do_deploy: Callable[[Web3, str], str],
):
```

**Comment by manindar-mohan** [comment]
Facing the same issue

**Comment by popelev** [comment]
same issue for "bank"
```
Traceback (most recent call last):
  File "/home/ctf/chal.py", line 5, in <module>
    eth_sandbox.new_launch_instance_action(deploy_value=Web3.toWei(50, 'ether')),
TypeError: new_launch_instance_action() got an unexpected keyword argument 'deploy_value'
```

**Comment by yassinebk** [comment]
Checking the `launcher.py` I found that the new function signature.
```py
def new_launch_instance( do_deploy : Callable[[Web3,str],str] ):
# Rest of code
```


## Fix

change the `deploy_value` to `do_deploy` so for example your `chal.py` for babyrev will become the following: 

```py
import eth_sandbox
from web3 import Web3


eth_sandbox.run_launcher([
    eth_sandbox.new_launch_instance_action(do_deploy=Web3.toWei(50, 'ether')),
    eth_sandbox.new_get_flag_action()
])
```

Happy Hacking !

**Comment by arih04x** [comment]
import eth_sandbox
from web3 import Web3

eth_sandbox.run_launcher([
    eth_sandbox.new_launch_instance_action(do_deploy=lambda w3, addr: w3.toWei(50, 'ether')),
    eth_sandbox.new_get_flag_action()
])
this is ok
